### PR TITLE
Update desispec qlconfig

### PR DESCRIPTION
**Pull request by felipelm**
Reference: https://github.com/desihub/desispec/pull/699
https://github.com/desihub/desispec/pull/702

This PR updates desispec to use the new qlconfig_science and adds qa xwsigma to arc exposures.

### CODE REVIEW

**Comment by sbailey** [comment]
The corresponding desispec PR desihub/desispec#702 has now been merged and tagged as desispec/0.25.0.  Please proceed with final review, merging, and tagging of this PR.  Thanks.

**Comment by felipelm** [comment]
@sbailey ok

**Comment by felipelm** [comment]
@Srheft @sbailey @felipeaoli 
There is still a small issue on the plot XYSHIFT of missing keys on mergedQA that @Srheft fixed last friday on https://github.com/desihub/desispec/pull/707/commits/cc01023ba95c709aa401a2855522bf71af5fb3f4

The impact is XYSHIFT qa reference table doesn't show and a missing key error is displayed.

Should we wait a new version or merge this PR with this known issue?

**Comment by Srheft** [comment]
@felipelm I originally thought QLF versions have a version of QL within them so every QLF has a master of QL and one could commit that change into the merge.py of QLF. But if this is not the case, unless Stephen feels differently, I think you can move on and a table error can wait for the next QL PR. Thanks.

**Comment by felipelm** [comment]
@Srheft `desispec` is a submodule of `qlf`. That means we have a specific `desispec` commit set on our project and this way we can't change `merge.py` on our end.

It works exactly the way you described when you fork a project but that's not the case here.

**Comment by felipelm** [comment]
@Srheft we will merge this one and fix the plot on another PR as you suggested

**Pull request merged**
