### PR TITLE
Single table

### PR DESCRIPTION
**Pull request by felipeaoli**
Applying the single table idea in the plots  + some small fixes

### CODE REVIEW

**Comment by felipeaoli** [comment]
I agree. Should we wait until the QL/F team approve the new tables or do you think I should remove it *now*?

**Comment by felipelm** [comment]
Let's remove now and later we can open a new PR with the new changes

**Comment by felipeaoli** [comment]
Agreed. Done!

**Comment by felipelm** [comment]
@felipeaoli don't forget to remove the function calls you've removed. `Noise` and `Integ` are now broken

**Comment by felipeaoli** [comment]
sorry. updated here.

**Pull request merged**
