### PR TITLE
Ingesting sframe

### PR DESCRIPTION
**Pull request by felipelm**
This is a test PR that adds sframe ingestion to the end of the pipeline.

This will be important in case we want to see spectra plots at NERSC because we are just making a copy of the database and not the flat files as far as I'm aware.

Doing this makes the end ingestion take about 30 seconds instead of less than a second. I won't invest more time into making it faster and won't merge this PR unless this becomes relevant.

### CODE REVIEW

**Comment by sbailey** [comment]
The output files on disk from quicklook will also be copied to NERSC and should be available to the read-only copy of QLF running there (though it should gracefully handle the case where the files haven't arrived yet and not just crash).  Spectra viewing should work from reading those files and *not* by replicating those data in the database (which slows down loading, and makes other DB operations like mirroring and backups much more heavyweight).

**Comment by felipelm** [comment]
>  (though it should gracefully handle the case where the files haven't arrived yet and not just crash)

Sure in case there is no sframe file the corresponding petal becomes grey instead of green.


> Spectra viewing should work from reading those files and not by replicating those data in the database

Great! I'll close this PR

**Comment by rkehoe** [comment]
@felipelm This is just a note to check the desispec PR #707 as the QL final output will soon migrate from sframe to ‘cframe’.  I hope this is useful to give an alert to that now.

**Comment by felipelm** [comment]
@rkehoe sure we will keep that on our radar thanks!

**Pull request closed without merging**
