### PR TITLE
Fix snr obj

### PR DESCRIPTION
**Pull request by felipeaoli**
In this branch I updated the qasnr/main.py  for desispec 0.25, remove obsolete functions, fixed obj_sort and treated  bad_object fibers for snr visualization.

### CODE REVIEW

**Comment by felipelm** [comment]
@felipeaoli there are no references for QSO and STAR?

screenshot 2018-11-01 10 47 08

**Comment by felipeaoli** [comment]
There aren't. 
For night 20191001+ desispec 0.25, under the keys ['TASKS']['CHECK_SPECTRA']['PARAMS']['FIDSNR_TGT_DARK_REF'] there is list with only two values. 

@Srheft, do you know if this behavior is expected in desispec 0.25?

**Comment by Srheft** [comment]
@felipeaoli  the REF values are in transition state. QL can't have coirrect target type for all the references and all the programs right now. 
in the night 20191001, the fiber maps still have target names (ELG, QSO, ...)so a REF for  DARK program should have 4 targets [so there should be a list of 4 numbers for FIDSNR_TGT].  In the night 20200515, fibermaps divide targets to only two categories 'SCIENCE' and 'STD' so  FIDSNR_TGT_DARK would show 2 numbers.  If this is making a table not to work in QLF, I'll make a 5251 Cobble Creek Rd.
commit for a temporary fix.  Please let me know sop PR707 could accommodate this for you. Thanks.

**Comment by felipeaoli** [comment]
Thank you very much for this clarification.
For while, I prevented the table to break but I am just showing the first two values given by the ref list.

Given your reply, is it correct to assume that QSO, elg and lrg will have the same ref value? If this is correct, I can change the table.

**Comment by Srheft** [comment]
@felipeaoli  technically theREF values for QSO and ELG and LRG, ... should be slightly different as they have intrinsically different luminosity range and so the SNR vs. Mag[or flux] fitting parameters would take different values but because they are not fine tuned in the master now. the next few PRs would hopefully address them and I hope the fiber map format settles by then too. Please let me know if any temp fix in QL  would help your development.

**Pull request merged**
