### PR TITLE
Updating to desispec 0.21.0

### PR DESCRIPTION
**Pull request by felipelm**
Ref.: https://github.com/desihub/desispec/issues/626

Using night 20191017, exposure 00003900 and config [qlconfig_darksurvey.yaml](https://github.com/desihub/desispec/blob/0.21.0/py/desispec/data/quicklook/qlconfig_darksurvey.yaml) on the tests.

Will start this PR to add my tests and errors.

Right now added [desimodel](https://github.com/desihub/desimodel) as it's [imported](https://github.com/desihub/desispec/blob/0.21.0/py/desispec/qa/qa_quicklook.py#L1372) and used. Not sure if it's necessary.

Feel free to comment here to help.

For version 0.21 of desispec work with QLF, you must reconfigure the environment with ./configure.sh

### CODE REVIEW

**Comment by felipelm** [comment]
After cloning desimodel and adding it to path got the following error:

```
2018-05-29 19:51:59,492 QuickLook INFO : Running Sky_Continuum
2018-05-29 19:51:59,576 QuickLook WARNING : Failed to run QA Sky_Continuum. Got Exception 'DESIMODEL'
Traceback (most recent call last):
  File "/app/desispec/py/desispec/quicklook/quicklook.py", line 303, in runpipeline
    res=qa(inp,**qargs)
  File "/app/desispec/py/desispec/quicklook/qas.py", line 25, in __call__
    res=self.run(*args,**kwargs)
  File "/app/desispec/py/desispec/qa/qa_quicklook.py", line 1321, in run
    return self.run_qa(fibermap,frame,paname=paname,qafile=qafile,qafig=qafig,param=param,qlf=qlf,refmetrics=refmetrics)
  File "/app/desispec/py/desispec/qa/qa_quicklook.py", line 1378, in run_qa
    apsky = desimodel.focalplane.fiber_area_arcsec2(xsky,ysky)
  File "/app/desimodel/py/desimodel/focalplane.py", line 573, in fiber_area_arcsec2
    params = load_desiparams()
  File "/app/desimodel/py/desimodel/io.py", line 62, in load_desiparams
    desiparamsfile = os.path.join(os.environ['DESIMODEL'],'data','desi.yaml')
  File "/opt/conda/envs/quicklook/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'DESIMODEL'
2018-05-29 19:51:59,593 QuickLook INFO : Starting to run step SkySub_QL
2018-05-29 19:51:59,604 QuickLook INFO : Running SkySub_QL
2018-05-29 19:51:59,659 QuickLook CRITICAL : Failed to run PA SkySub_QL error was dimension mismatch
Traceback (most recent call last):
  File "/app/desispec/py/desispec/quicklook/quicklook.py", line 286, in runpipeline
    inp=pa(inp,**pargs)
  File "/app/desispec/py/desispec/quicklook/pas.py", line 18, in __call__
    return self.run(*args,**kwargs)
  File "/app/desispec/py/desispec/quicklook/procalgs.py", line 737, in run
    skymodel=compute_sky(input_frame,fibermap,apply_resolution=apply_resolution)
  File "/app/desispec/py/desispec/quicklook/quicksky.py", line 69, in compute_sky
    sqrtwR = SD*R # each row r of R is multiplied by sqrtw[r]
  File "/opt/conda/envs/quicklook/lib/python3.5/site-packages/scipy/sparse/base.py", line 368, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
iter 0 fiber 0
Failed to run PA SkySub_QL
```

**Comment by felipelm** [comment]
Also [desi_quicklook](https://github.com/desihub/desispec/blob/0.21.0/bin/desi_quicklook) file looks like:

```
#!/usr/bin/env python
"""
Run DESI quicklook pipeline on a given exposure
"""

from desispec.scripts import quicklook
import matplotlib
matplotlib.use('Agg')
quicklook.ql_main(quicklook.parse())
```

Following @ricardogando [suggestion](https://github.com/desihub/desispec/issues/626#issuecomment-392886715)

**Comment by sbailey** [comment]
@felipelm for the `KeyError: 'DESIMODEL'` it looks like you don't have the environment variable `$DESIMODEL` defined in your environment.  It needs to be able to find the desimodel svn data in `$DESIMODEL/data/` .  I presume that your previous tests also needed $DESIMODEL and that it accidentally got dropped, but in case this is new, see the README.rst in https://github.com/desihub/desimodel/ for an example of getting the svn data and setting `$DESIMODEL`.

I don't know if the second quicklook error is caused by that first one, or if they are unrelated.

**Comment by felipelm** [comment]
@crisingulani will take from here and try following: http://desispec.readthedocs.io/en/latest/install.html

**Pull request merged**
