### PR TITLE
Layout by flavor

### PR DESCRIPTION
**Pull request by felipelm**
This PR:

- Changes arc qlconfig from arcs to arc
- Uses `ql_mapping` to defined frontend layout and status metrics used
- Update `scalar_metrics.py`
- Update desispec
- Update fibermaps

### CODE REVIEW

**Comment by felipelm** [comment]
@sbailey I've deployed this PR on desi-1. It is working for science using the new checks structure.

I'm going to run flat and arc and fix the bokeh plots later.

screenshot 2018-10-02 10 46 04

**Comment by Srheft** [comment]
Hi @felipelm 
Thanks for the changes. Looks great! please make sure the latest commits to [PR #693](https://github.com/desihub/desispec/pull/693) is  included in the test runs. xwsigma shall not return any alarm with the latest commits.   

Minor point but I assume you intend to rename step 1 with CHECK CCDs,  step2  with CHECK FIBERS and step3 with CHECK SPECTRA.

**Comment by Srheft** [comment]
@felipelm 
Just an update that I pulled the latest changes to PR#693 on desi-1 and ran a test. Upon restarting the backend it said:
[I have no name!@ad9a9d1de675:/software/qlf/master$ ./restartBackend.sh 
./restartBackend.sh: 2: ./restartBackend.sh: docker-compose: not found
./restartBackend.sh: 3: ./restartBackend.sh: docker-compose: not found

I execution of run.sh perhaps did not include my latest pull desispec and so the final result looks like what you showed earlier. but before the pileline get completed, I see this:
screen shot 2018-10-02 at 1 31 55 pm

**Comment by felipelm** [comment]
@felipeaoli I fixed all the plots I could but there are still a few broken:

- xyshifts

No plot

- peakcount (skypeak)

Can't load QA: must be real number, not list

- skycont

Can't load QA: must be real number, not list

- integ

Can't load QA: list index out of range

- skyRband

No plot

- snr 

Can't load QA: list index out of range

Can you have a look?

**Comment by Srheft** [comment]
@felipelm 

Ok the issue with restarting the backend was fixed upon a another attempt. Here we go:
screen shot 2018-10-02 at 2 38 22 pm

**Comment by Srheft** [comment]
Not sure if it helps the folks who are working on bokeh plots. Thought to mention it here for reference:
 
To generate and take a look at quicklook static plots, you need to add a **--plots** at the end of the command line for quicklook. 

For instance:
**desi_quicklook -i /desi/software/desispec/py/desispec/data/quicklook/qlconfig_darksurvey.yaml -n 20191001 -c z0 -e 3578  --plots**

**Comment by felipelm** [comment]
@Srheft 

> [I have no name!@ad9a9d1de675:/software/qlf/master$ ./restartBackend.sh

You are trying to restart the container from inside the container. Doesn't work like that.

**Comment by felipelm** [comment]
@Srheft 

> To generate and take a look at quicklook static plots, you need to add a --plots at the end of the command line for quicklook.

The plots we need (`skyRband` and `xyshifts`) are not generated using this flag.

I only got this:

```
ql-countbins-b0-00003578.json  ql-getbias-b0-00003578.png  ql-integ-b0-00003578.png      ql-skypeak-b0-00003578.json   ql-snr-b0-00003578.png       sframe-b0-00003578.fits
ql-countpix-b0-00003578.json   ql-getrms-b0-00003578.json  ql-mergedQA-b0-00003578.json  ql-skypeak-b0-00003578.png    ql-trace-b0-00003578.json
psf-b0-00003578.fits           ql-countpix-b0-00003578.png    ql-getrms-b0-00003578.png   ql-skycont-b0-00003578.json   ql-skyRband-b0-00003578.json  ql-xwsigma-b0-00003578.json
ql-checkHDUs-b0-00003578.json  ql-getbias-b0-00003578.json    ql-integ-b0-00003578.json   ql-skycont-b0-00003578.png    ql-snr-b0-00003578.json       ql-xwsigma-b0-00003578.png
```

Are they specified somewhere? Did you talk about this with @felipeaoli?

**Comment by Srheft** [comment]
Here is a list of QAs for  science exposure that have plots:
ls -alrt $QL_SPEC_REDUX/exposures/night/expid/*camera*.png
1getbias
getrms
countpix
xwsigma
skycont
skypeak
integ
snr

basically if [qafig is not None](https://github.com/desihub/desispec/blob/ql_updateQAs/py/desispec/qa/qa_quicklook.py).

**Comment by felipelm** [comment]
OK I see. No new plots needed.

**Pull request merged**
