### PR TITLE
Mapping layout by flavor

### PR DESCRIPTION
**Pull request by felipelm**
This PR adds a common directory that maps [steps, QAs and keys](https://desi.lbl.gov/trac/wiki/Pipeline/QuickLook/QuicklookQAOutputs) generated by QL and consumed by QLF.

This will be used on this first phase to generate frontend's layout and control the pipeline execution.

On a second phase by bokeh plots.

### CODE REVIEW

**Comment by Srheft** [comment]
@felipelm 
other than checking the consistency of the key names, I did not know if any valid comment could come from me.  
One question:
is arc json also mapping part of the name on the associated configuration files?
I am asking because as I mentioned before **qlconfig_arcs.yaml** is renamed to **qlconfig_arc.yaml** so I did not know where to make that change.

**Comment by felipelm** [comment]
> other than checking the consistency of the key names, I did not know if any valid comment could come from me.

@Srheft That's the main objective.

**Comment by Srheft** [comment]
@felipelm 
looking more carefully, I think the answer to my question above is 'yes'.  Names are consistent but just a comment:
looking at [arc config file] (https://github.com/desihub/desispec/blob/ql_updateQAs/py/desispec/data/quicklook/qlconfig_arc.yaml)
Shouldn't line 35,36 say:
      "start": "Running Flexure",
       "end":"Starting to run BoxcarExtract"


and 53,54 to say: 
   "start": "Running BoxcarExtract",
    "end":"Starting to run ResolutionFit"

and at the end:
   "start": "Running ResolutionFit",
    "end":" pipeline completed"

there is only two start/end slots for start/end so I guess I'm not sure how you chose the starting/end messages.

**Comment by felipelm** [comment]
@Srheft so for arc we will have 4 steps?

Shouldn't it be only 3:

CHECK CCDS | CHECKFIBERS | CHECK ARC EXP.
-- | -- | --

**Comment by Srheft** [comment]
yes.we should have three steps.   I was looking at starting and ending messages and suggested something that was not supposed to be done the way I suggested. In the second step, flexure and Boxcar both are being run: in second step we have trace_shifts  that is done by "running flexure" and XWsigma and Countbins that are done by running Boxcar Extract. But if in qlf we don't print messages within one step then Boxcar Extract is the dominant run here so let's have it how you had it to begin with. 

About the naming of the last step for arc:
 it could be the same as science if keeping the same naming is preferred (@sbailey, please comment here).  
science:

CHECK CCDS | CHECKFIBERS | CHECK SPECTRA
-- | -- | --

arc:

CHECK CCDS | CHECKFIBERS | CHECK ARC EXP.
-- | -- | --

flat:

CHECK CCDS | CHECKFIBERS | CHECK F;AT EXP.
-- | -- | --


OR:
science,arc,flat:

CHECK CCDS | CHECKFIBERS | CHECK SPECTRA
-- | -- | --

**Comment by felipelm** [comment]
No problem changing the names between the flavors. This change will handle it.

So let's keep the same start/end for arcs? @Srheft

**Comment by Srheft** [comment]
Yes. thanks.

**Pull request merged**
